import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Register from "@/components/auth/Register";
import Login from "@/components/auth/Login";
import QueryProvider from "@/context/query-provider";
import { Suspense } from "react"; // استيراد Suspense

export const metadata: Metadata = {
  title: "Turbo Cars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black antialiased`}>
        <QueryProvider>
          <Suspense fallback={<div>Loading...</div>}>
            <NuqsAdapter>
              <Register />
              <Login />
              {children}
            </NuqsAdapter>
          </Suspense>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}